POST https://sievalhub.sieval.com/api/productiondata/document/generatePdfDocument?productionDocumentId=38
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijc1NjQiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJTb2ZpZW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiQ1BUIiwiZW1wbG95ZWVEZXZpY2UiOiI1N2FhZjZhYS1hZGU4LTRhMWUtODUxYy1mZjZhM2FjNTg5OGUiLCJlbXBsb3llZVR5cGUiOiIwIiwibGljZW5zZWVJZCI6IjEyOTkiLCJ1c2VySWQiOiI0MDciLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9oYXNoIjoiNzRFOTJBNkIiLCJleHAiOjE3NzgxNTU5MDgsImlzcyI6Imh0dHA6Ly9zaWV2YWxodWIuc2lldmFsLmNvbS8iLCJhdWQiOiJodHRwOi8vc2lldmFsaHViLnNpZXZhbC5jb20vIn0.lyyeWyFoU5G9pr79pTxt5cWuyXhmdpMyEKwxiyxVeRk
Content-Type: application/json
Origin: https://app.decoloop.com
Referer: https://app.decoloop.com/

{
  "productionProjectId": 212117,
  "productionPolygonIds": [578409,578410,578411],
  "languageCode": "fr"
}